---
title: Can Change in Forest Mass Across Time Predict Biodiversity?
format: closeread-html
---

:::{.cr-section}Introduction
Biodiversity of the world makes living in the world a wondrous experience, and is crucial for survival of human beings. The world houses countless complex interactions between different species that maintain a delicate balance for the sustenance of life. This balance has been preserved for the past millions of years with change in dynamics that resulted in extinction of some species and evolution of others. 

With human-kind's taking precedence in the recent world history, this million year-old ecosystem balance started to experience intense fluctuations. What started with the Industrial Revolution led to a massive emission of green house gasses that endangered the Ozone Layer and gradually raised the temperature of the Earth through various mechanisms. Moreover, humans have shown small regard for life of other beings for the sake of earning money over them, causing the extinction and endangerment of so many including ...,...,... The harm committed by humans on nature include massive clearings of the forest and converting those lands into fertile farm-lands. This, together with wildfires, results in accelerating rates of deforestation, especially at the critical oxygen-producing regions including the Congo Rainforest and the Amazon Rainforest. 

Rainforests are homes to the most diversity of life on the planet, and are critical sources of oxygen production and carbon trapping for the world. A world without rainforest is inhabitable by any living beings, and gradual destruction of rainforests is having many adverse affects, one of which include loss of biodiversity. 

We are a group of two people who are passionate about animals, birds specifically. Birds are relatively harder to keep track of due to them inhabiting nests dozens of feet above the ground and are being smaller in size. Compared to land animals and larger animals, making an estimate of the number of a specific bird species in the world is relatively harder. Therefore, we wanted to develop models that would take in different deforestation variables including new forest loss, new forest gain, net forest change, stable forest kept, all of which are related to each other, and predict the number of unique species of birds dependent on the change in forests. Our model will allow us to predict how hypothetical changes in forest sizes will affect bird populations in the future, which can be very useful in developing policies that prioritize biodiversity, by making the threat of many animal's extinction obvious through data. 
:::
:::{.cr-section}Methods
We got our deforestation data from www.globalforestwatch.org and our bird species data from gbif.org. 

How our deforestation dataset looks like:
#insert deforestation dataset look
How our bird dataset looks like:
#insert bird dataset look

To understand the impacts of deforestation, we used the Deforestation dataset, and calculated the 10 countries with the most negative forest size change between 2000-2020, and the 10 countries with the most positive forest size change between 2000-2020. Among these 10 countries for each category, we chose 5 that had enough datapoints so we could conduct analysis, but not too much data like Brazil or the US, that would take up GigaBytes of memory in our computers. The countries we chose for each category are outlined below:
Highest Net Forest Loss: 
Paraguay(PRY), Democratic Republic of Congo(COD), Mozambique(MOZ), Indonesia(IDN), Tanzania(TZA)
Highest Net Forest Gain:
Uruguay(URY), Ukraine(UKR), Poland(POL), Ireland(IRL), Bangladesh(BGD)
There are more than a dozen bird orders on the GBIF database, with some species including on the order of millions of datapoints. Therefore, to cut down on memory use, in addition to chosing countries wisely, we chose 4 orders in total, representing life in different ecosystems. Two of the four selected orders are Coraciiformes, 
Strigiformes, both of whom live in forests and woodlands. The third order is galliformes who live on shrublands, and the last order is Ciconiiformes who live on wetlands. We wanted to capture as much variance possible with our selection of bird orders. 
Lastly, the GBIF database offers observations starting 1900, all the way until the present. For lower memory consumption purposes, we only acquired data from years 2000, 2010, and 2020, in parallel with the time span captured by the deforestation data. 

1.We downloaded all the data and preprocessed variables (changing char to doubles, getting rid of unnecessary variables like ID, changing country codes to country names for consistency). 
2.We merged two datasets to have one dataset that looked like this:
#dataset with both bird data, and the deforestation data
3.We calculated the counts of each bird order in each country, and tracked their change across time:
#10 plots of order counts accross time
4.We visualized the geospatial change of bird order concentrations across time. Our deforestation data don't unfortunately provide detail into location of forest lost and gained, so it's hard to infer correlations between changes in bird number concentrations and changes in forests. 
#40 heat maps of each bird order's changing count concentration accross time
5. We then trained a kNN, a SVM, and a Random Forest on our deforestation data with the outcome variable being the change of the count of that bird order in that country. 
#it's currently implemented to predict the exact value of bird order counts. Change the dataframe such that instead of bird counts
#1. we have bird count change from 2000-2020. So for each bird order for each country, there will be one value.
#We intend to find correlations, to see if deforestation parameters can predict change in population of a bird order by being consistent across countries. 
6. We analyzed the networks performance, concluded that we expect some correlation for bird species inhabiting forests. 
7. Make creative visuals. Make further assumptions.

Thank you for following along. This work was done by Ulas Ayyilmaz and Ishika Keswani as a  final project in our Computational Statistics Class, led by Jo Hardin <3. 

:::